import { CarouselContainer } from "@/components/Home/in/CarouselContainer";
import { FormContainer } from "@/components/Home/in/FormContainer";
import { LastContainer } from "@/components/Home/in/LastContainer";
import { MiddleContainer } from "@/components/Home/in/MiddleContainer";
import { RoadMapContainer } from "@/components/Home/in/RoadMapContainer";
import { StagesContainer } from "@/components/Home/in/StagesContainer";
import { TopContainer } from "@/components/Home/in/TopContainer";
import { WhyIVFContainer } from "@/components/Home/in/WhyIVFContainer";
import { Layout } from "@/components/Layout/Layout";
import Head from "next/head";
import { useReducer } from "react";

export default function Home() {
  const formRef = useReducer(null);

  const scrollToForm = () => {
    formRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <title>Home IVF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout scrollToForm={scrollToForm}>
        <TopContainer scrollToForm={scrollToForm} />
        <FormContainer formRef={formRef} /> {/* Done */}
        <StagesContainer scrollToForm={scrollToForm} /> {/* Done */}
        <RoadMapContainer /> {/* Done */}
        <MiddleContainer scrollToForm={scrollToForm} /> {/* Done */}
        <WhyIVFContainer /> {/* Done */}
        <CarouselContainer scrollToForm={scrollToForm} /> {/* Done */}
        <LastContainer /> {/* Done */}
      </Layout>
    </>
  );
}
