import { FormContainer } from "@/components/Home/FormContainer";
import { MiddleContainer } from "@/components/Home/MiddleContainer";
import { RoadMapContainer } from "@/components/Home/RoadMapContainer";
import { StagesContainer } from "@/components/Home/StagesContainer";
import { TopContainer } from "@/components/Home/TopContainer";
import { WhyIVFContainer } from "@/components/Home/WhyIVFContainer";
import { Layout } from "@/components/Layout/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home IVF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <TopContainer />
        <FormContainer /> {/* Done */}
        <StagesContainer /> {/* Done */}
        <RoadMapContainer /> {/* Done */}
        <MiddleContainer /> {/* Done */}
        <WhyIVFContainer />
      </Layout>
    </>
  );
}
